name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create config.ini
      run: |
        echo "[authentication]" > config.ini
        echo "username=${{ secrets.USERNAME }}" >> config.ini
        echo "password=${{ secrets.PASSWORD }}" >> config.ini
        echo " " >> config.ini
        echo "city_url=${{ secrets.CITY_URL }}" >> config.ini
        echo "hotel_url=${{ secrets.HOTEL_URL}}" >> config.ini 
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
